### ISSUE TITLE
Cannot resolve simpleName on Class object

### ISSUE THREAD

**Issue by rmuller** [trimou/trimou#107]
This does not work:

    @Test
    public void testGetSimpleName() {
        MustacheEngine engine = MustacheEngineBuilder.newBuilder()
            .build();
        
        assertEquals(Integer.class.getSimpleName(), 
            engine.compileMustache("testTemplate", "{{simpleName}}").render(Integer.class));
    }

Result:

expected:<[Integer]> but was:<[]>

Is this a bug or am i missing something?

**Comment by mkouba** [comment]
You're right, this is a bug. There is a special handling for enums (to allow to use `enumClazz.values()` and `enumClazz.CONSTANT` in templates) which prevents invoking `Class<?>` methods.

Thanks for reporting!
