### ISSUE TITLE
Feature request: Allow (java 8) Stream instances to be used for sections

### ISSUE THREAD

**Issue by rmuller** [trimou/trimou#108]
If a variable resolves to a `Stream` instance, it is handled like a Collection / Array. So "iterating" over all values.

The issue is that a growing number of API's return `Stream` instances instead of `Collection` or array objects.

**Comment by mkouba** [comment]
Hm, there are few problems with `Stream`. First of all streams should be only used once, e.g. like an `Iterator` you can't iterate over the stream multiple times (this might lead to incorrect/unpredictable results). Also we wouldn't be able to provide some iteration meta info (such as `isLast`). On the other hand, I agree that currently there is no easy solution to iterate over a `Stream` instance.

**Comment by rmuller** [comment]
Yes, you are right. There not something like `Streamable` (like `Iterable` for `Iterator`).
I am bound to a certain API, so must deal with the `Stream` producing methods. Is a custom resolver the best way to tackle this?

**Comment by mkouba** [comment]
Hm, I think we can consider adding the `Stream` support directly in core. The best way to work around this right now would be a custom helper. Something like this should work:

```java
import java.util.stream.Stream;

public class StreamHelper implements Helper {

    @Override
    public void execute(Options options) {
        Object param = options.getParameter(0, null);
        if (param != null && param instanceof Stream) {
            try (Stream<?> stream = (Stream<?>) param) {
                stream.sequential().forEach((e) -> {
                    options.push(e);
                    options.fn();
                    options.pop();
                });
            }
        }
    }
}
```
and in template:
```
{{#stream foo.getStream}}
do something with element
{{/stream}}
```

**Comment by rmuller** [comment]
Thank you for your fast replies and excellent example. Much appreciated! 

As a side note: you can just write `if (param instanceof Stream) {` 

(see https://stackoverflow.com/a/2950415/868941).

**Comment by mkouba** [comment]
> As a side note: you can just write...

Sure, that was just a quick and dirty snippet ;-)

**Comment by mkouba** [comment]
By the way, another workaround using `with` and `repeat` helpers:
```
{{#with anyStream.sequential.iterator}}
  {{#repeat while=hasNext}}
    Element toString(): {{next}}
  {{/repeat}}
{{/with}}
```

**Comment by rmuller** [comment]
Thanks for the tip. Prefer the helper approach, which is already implemented and works great.
