### ISSUE TITLE
Publish the JavaDoc as part of the documentation

### ISSUE THREAD

**Issue by rmuller** [trimou/trimou#110]
For a better getting started experience having the latest JavaDoc by hand would be handy.

**Comment by mkouba** [comment]
Good point. The javadoc is in Maven central repo so that it's easy to setup your favorite IDE to download the artifacts and make it available. But I agree that it might be useful to have the latest one published.

**Comment by rmuller** [comment]
> The javadoc is in Maven central repo so that it's easy to setup your favorite IDE to download the artifacts and make it available.

Yes, agree. I have the "mmm, looks interesting" target audience in mind

**Comment by mkouba** [comment]
Fixed: http://trimou.org/doc/javadoc/index.html
