### ISSUE TITLE
How to get the trimou version?

### ISSUE THREAD

**Issue by rmuller** [trimou/trimou#111]
We aim to add trimou as template engine to our application. The User should be able to select the template engine. A nice-to-have feature is to be able to display the version number (of the selected template engine). Is this available via the standard api? Version string is sufficient.

**Comment by rmuller** [comment]
AFAIK this info is only logged by MustacheEngineBuilder#build() and not exposed the the API.

**Comment by mkouba** [comment]
Yes, it's not possible to get the version through API. We could add `MustacheEngine.getVersion()` in the next release. For now, the workaround would be to inspect the `trimou-build.properties` (included in `trimou-core`): 
https://github.com/trimou/trimou/blob/master/core/src/main/java/org/trimou/engine/MustacheEngineBuilder.java#L146-L162

**Comment by rmuller** [comment]
Thanks again for the fast reply. `MustacheEngine.getVersion()` is indeed what i expected. No problem however.
