### ISSUE TITLE
Access (via API) to ELProcessor (trimou-extension-el 2.0.3)

### ISSUE THREAD

**Issue by rmuller** [trimou/trimou#112]
When working with EL 3.0 in a non-trivial setup access to ELProcessor / ELManager is needed, so custom resolvers / type converters can be added.

For an example use-case, see https://stackoverflow.com/a/46581099/868941.

**Comment by mkouba** [comment]
Hm, we could introduce something like `ELProcessorFactory` and EL extension-specific config property (class or instance) to set this factory.

**Comment by rmuller** [comment]
Yes, because in the current setup i see no other solution than using a modified (custom) ELHelper (not a big deal btw). Need to dive somewhat deeper into this :)

**Comment by mkouba** [comment]
@rmuller It would be great if you could review/test the proposed API:
https://github.com/trimou/trimou/blob/master/extensions/el/src/main/java/org/trimou/el/ELProcessorFactory.java

Ideally, build the project and test the snapshot for your use case.

**Comment by rmuller** [comment]
Great! I will do. Will not be today, but Monday latest.

**Comment by rmuller** [comment]
Hi Martin,

First of all, your support for this project is just great. Thanks a lot. Our complete use-case is now supported by this library.

My findings:

+ Building project: no issues
+ Using the new features: works like a charm. API is also clear and easy to use but yet powerful (although the ELProcessorFactory#convert option is maybe a little overkill, but i realize it makes it even more flexible)
+ One (minor) comment: `ELProcessorFactory` should be annotated with `@FunctionalInterface`
+ Tested all my use-cases: all are passing now.

FYI, we are now able to do this kind of cool stuff:

```` 
{{! context: Product[232003] }}
{{#each "this.findResources(r->r.getContentType() eq 'image/png', false)"}}
{{.}}
{{/each}}
````

**Comment by rmuller** [comment]
An extra note: A disadvantage of the current setup is that for every EL expression, a new `ELProcessor` is used. This is not a big issue, but i prefer to have a single instance of `ELProcessor` for a session / "template rendering context". This is currently not possible, because every time  a new `OptionsELResolver` is added to the  `ELProcessor`.

**Comment by rmuller** [comment]
Last remark. With the new behavior of the ELEachHelper, the ELIfHelper should be adapted in the same way to be consistent so we can write `{{#if person}}{{name}}{{/if}}` instead of `{{#if person}}{{person.name}}{{/if}}`. What do you think?

**Comment by mkouba** [comment]
> ELProcessorFactory#convert option is maybe a little overkill

Yep, we need this so that a properties file can be used to specify a factory class.

> FYI, we are now able to do this kind of cool stuff:

Interesting beast... but I wouldn't want to debug this ;-)

> A disadvantage of the current setup is that for every EL expression, a new ELProcessor...

Yes, exactly. Otherwise we would have to use `ThreadLocal`s and that's something I would like to avoid.

> ELIfHelper should be adapted...

I don't think so. `IfHelper` has a well-defined behavior and it might be confusing.

**Comment by rmuller** [comment]
Thanks for the clarifications.

> I don't think so. IfHelper has a well-defined behavior and it might be confusing.

You are right. Just checked the "official" handlebars doc: 

> Control structures typically do not change the current context, instead they decide whether or not to invoke the block based upon some variable

Should have checked this first :(
