### ISSUE TITLE
Iterator not supported for sections?

### ISSUE THREAD

**Issue by rmuller** [trimou/trimou#120]
I am converting some templates from jmustache to trimou. This one fails for trimou. Hope the test case is clear enough.

```
@Test
public void testIterator() {
    //stupid example
    final Map<String, Object> context = new HashMap<>();
    context.put("foo", new Iterator<String>() {

        private String s = "abc";
        private int index;

        @Override
        public boolean hasNext() {
            return index < s.length();
        }

        @Override
        public String next() {
            return Character.toString(s.charAt(index++));
        }

    });

    assertEquals("abc", // okay
        com.samskivert.mustache.Mustache.compiler()
        .compile("{{#foo}}{{.}}{{/foo}}")
        .execute(context));

    assertEquals("abc",  // fails expected:<[abc]> but was:<[test.trimou.TrimouTest$1@fad74ee]>
        org.trimou.engine.MustacheEngineBuilder.newBuilder()
        .build()
        .compileMustache("{{#foo}}{{.}}{{/foo}}")
        .render(context));
}
```

**Comment by mkouba** [comment]
Yes, in trimou `Iterator` (and `Stream`) is only supported in `EachHelper`, i.e. `{{#each foo}}{{.}}{{/each}}` should work. I don't think we should add support for mustache section tag. First of all, `Iterator` can only be used once, also we wouldn't be able to provide some iteration meta info (such as `isLast`).

**Comment by rmuller** [comment]
Clear. However, then I have another issue: how to *only* register the each helper?

Background: In our app, mustache templates are used internally and by end users. Internally we make use of advanced features offered by trimou (like ELHelper). This was the main reason for switching to trimou.
For end users we only offer a "minimal" environment (currently pure mustache using jmustache). So if we need to enable the each-helper, I do not want to unlock the other possibilities too. Another option is to leave it as it is. But that does not feel right, using two different libraries for the same purpose.

**Comment by mkouba** [comment]
So you're using one `MustacheEngine` internally and one for end users? If so, you have full control over the features provided. You can start with `MustacheEngineBuilder.omitServiceLoaderConfigurationExtensions()` - this will skip automatic configuration. Then register basic resolvers with `MustacheEngineBuilder.addResolver()` (see for example `DefaultConfigurationExtension.register()`) and `EachHelper` with `MustacheEngineBuilder.registerHelper()`.

**Comment by rmuller** [comment]
Ahhh Yes!. I missed `omitServiceLoaderConfigurationExtensions()`

**Comment by rmuller** [comment]
FYI: The two most popular mustache implementations for Java (mustache.java and jmustache) both support `Iterator` for sections. Handlebars.java does not.
(tested latest versions of these libraries)
