### ISSUE TITLE
Needs a way to nest helper arguments?

### ISSUE THREAD

**Issue by rnikander** [trimou/trimou#122]
I have a template with a bindings for x="aaa" and y="bbb".  I need to pass the string "aaabbb" to a helper `foo`, as an argument, like:

    {{ foo x + y }}  

Is there a way to do this, or something like it? It seems so simple yet I don't see a way to do it. With a helper `concat` I could do it if I could nest {{ }}...

    {{ foo {{ concat x y }} }}

**Comment by mkouba** [comment]
You could make `concat` a section helper (something like https://github.com/trimou/trimou/blob/master/core/src/main/java/org/trimou/handlebars/WithHelper.java#L29) and push the concatenated value on the stack:
```
{{#concat x y}}
  {{foo this}}
{{/concat}}
```
Or just use **EL extension** and [el helper](http://trimou.org/doc/latest.html#_elhelper):
```
{{#el "x += y"}}
  {{foo this}}
{{/el}}
```
We don't plan to support tags nested inside a tag definition.

**Comment by mkouba** [comment]
@rnikander Feel free to reopen if you need more info ;-)
