### ISSUE TITLE
handlebars.java's Context build combine()?

### ISSUE THREAD

**Issue by muryoh** [trimou/trimou#124]
Hey,

First things first, thanks for the great library :+1: 

I'm currently thinking about how to use it and would like to know if there is something similar (or an alternative) to [handlebars.java's Context build combine() operation](https://github.com/jknack/handlebars.java#extending-the-context-stack)

My use case is basically the following: in the view, I will have access to objects that I would like to be able to "enrich" on the fly depending on the template's needs.

For example, let us say those objects are instances of class "Cat", with attributes "size" and "weight"
In a template, I may write
```
Size: {{size}}
Weight: {{weight}}
```

Given "overweight" as an extra property computed by the view depending on the size/weight, I would like to be able to write
```
Size: {{size}}
Weight: {{weight}}
Overweight: {{overweight}}
```
But without having to:

1. tinker with the Cat class (adding the overweight field is a no-go)
2. having to create a new class that would copy Cat's fields 

Is there such a feature "built-in" in Trimou?

Cheers :-)

**Comment by muryoh** [comment]
Note that I realize in the end that feature of handlebars.java only works for the "root" context
Ideally I would like to be able to do that for any level of the context

**Comment by mkouba** [comment]
Hey @muryoh and thanks for the report! We don't have a similar feature in trimou yet. In fact, there is no concept of explicit `Context` in trimou. But it seems to be a very useful feature. So let's think about how this should work...

**Comment by mkouba** [comment]
So one way to accomplish this would be to use a custom helper that pushes the additional values on the stack before the `Cat` instance (if no value is resolved on the `Cat` instance trimou will try the next object on the stack), e.g.:
```java
class CombineHelperTest {

    @Test
    public void testHelper() {
        final MustacheEngine engine = MustacheEngineBuilder.newBuilder().registerHelper("enhancedCat", (options) -> {
            Cat cat = (Cat) options.peek();
            options.push(ImmutableMap.of("overweight", cat.getWeight() > 4500 ? cat.getWeight() - 4500 : 0));
            options.push(cat);
            options.fn();
            options.pop();
            options.pop();
        }).build();

        List<Cat> cats = new ArrayList<>();
        cats.add(new Cat("Mikes", 3000));
        cats.add(new Cat("Mourek", 5000));
        assertEquals("Cat Mikes [3000g] has overweight 0g.Cat Mourek [5000g] has overweight 500g.",
                engine.compileMustache(
                        "{{#each this}}{{#enhancedCat}}Cat {{name}} [{{weight}}g] has overweight {{overweight}}g.{{/enhancedCat}}{{/each}}")
                        .render(cats));
    }

    class Cat {

        private final String name;

        private final Integer weight;

        public Cat(String name, Integer size) {
            this.name = name;
            this.weight = size;
        }

        public String getName() {
            return name;
        }

        public Integer getWeight() {
            return weight;
        }
    }
}
```
But it's too verbose. A simple builder for similar helpers might be useful.

**Comment by mkouba** [comment]
@muryoh This [branch](https://github.com/mkouba/trimou/tree/decorator-helper) (WIP) contains two proposals. 

First is using a helper to decorate an instance during template execution: https://github.com/mkouba/trimou/blob/decorator-helper/core/src/test/java/org/trimou/handlebars/DecoratorHelperTest.java#L22-L37

The second one is using a more general approach - you can use a `Decorator` to wrap the data you pass to the engine: https://github.com/mkouba/trimou/blob/decorator-helper/core/src/test/java/org/trimou/engine/resolver/DecoratorTest.java#L17-L20

Let me know if any of this solution matches your requirements...

**Comment by muryoh** [comment]
Hi @mkouba 

The second one is exactly what I had in mind :-)
It is perfect because for my use case because...

In my use case, the engine will be setup by a framework and used by users that will **not be able to register helpers**. Therefore solution one was a no-go for me. Also, the decoration can **easily be done in the context** that users will provide along with their template (although ideally we don't want them to have access to the engine instance, but we can easily provide an API to hide it)

We may need to **add levels to enriched data**. ie, in your example, we could be wanting to add a list of Nail to each Hammer, decorating each Nail:
`decorate(h).map("nails", listOf(nails)`

Your implementation allows that, which is perfect. It's starting to get ugly, but it would become 
```
decorate(h).map("nails", listOf(nails)
     .map(nail -> decorate(nail).map("size", randomInt()).build()
)
```

:100: for me :+1:

**Comment by mkouba** [comment]
FYI I've also added `ContexConverter` API which allows to define "global" decorators, see for example https://github.com/trimou/trimou/blob/master/core/src/test/java/org/trimou/engine/convert/DecoratorConverterTest.java. I know that it's probably not suitable for you framework but it could be useful ;-)
