### ISSUE TITLE
wrong date format in example

### ISSUE THREAD

**Issue by alexei-grigoriev** [trimou/trimou#129]
There is an [example](http://trimou.org/doc/latest.html#_datetimeformatresolver_example) for DateTimeFormatHelper. It suggests to use `{{formatTime now pattern="DD-MM-yyyy HH:mm"}}` but this format string is not valid. DD stands for "Day in year", two digits and you need 3 digits to represent days after April, 9 (99-th day).

Not a big issue but confusing enough to want it fixed.

**Comment by mkouba** [comment]
@alexei-grigoriev Thanks for spotting this. Feel free to send a PR ;-).
