### ISSUE TITLE
Unable to get java.util.Date instance for PrettyTime (from a long stored as json with `trimou-extension-json-p`)

### ISSUE THREAD

**Issue by avp90** [trimou/trimou#131]
We use Trimou with the following dependencies:
```
  "org.trimou" % "trimou-core" % "2.5.0.Final",
  "org.trimou" % "trimou-extension-json-p" % "2.5.0.Final",
  "org.trimou" % "trimou-extension-el" % "2.5.0.Final",
  "org.trimou" % "trimou-extension-prettytime" % "2.5.0.Final"
```

In our `mustache.render()` we add one or more JsonObjects with dates (stored in json as `Long`). In a template we want to do something like this:
`{{pretty requestContext.requestDate locale='de'}}`
  
The convert function in [PrettyTimeHelper.java#L120](https://github.com/trimou/trimou/blob/master/extensions/prettytime/src/main/java/org/trimou/prettytime/PrettyTimeHelper.java#L120) is called with the value from [JsonValueResolver.java#L140](https://github.com/trimou/trimou/blob/master/extensions/json-p/src/main/java/org/trimou/jsonp/resolver/JsonValueResolver.java#L140). But the Value is a `java.math.BigDecimal` (not `java.lang.Long`) after [JsonValueResolver.java#L140](https://github.com/trimou/trimou/blob/master/extensions/json-p/src/main/java/org/trimou/jsonp/resolver/JsonValueResolver.java#L140) and the converter [ObjectToDateConverter.java#L61](https://github.com/trimou/trimou/blob/master/core/src/main/java/org/trimou/engine/convert/ObjectToDateConverter.java#L61) don't know the given type and need a `Long`.

A `MustacheException` with the following message is thrown in [PrettyTimeHelper.java#L122](https://github.com/trimou/trimou/blob/master/extensions/prettytime/src/main/java/org/trimou/prettytime/PrettyTimeHelper.java#L122):
`org.trimou.exception.MustacheException: RENDER_HELPER_INVALID_OPTIONS: Unable to get java.util.Date instance for PrettyTime [template: 22222222-db4a-455a-9423-9e9e556a9e65, line: 31, param: 1557993944632]`

**Comment by mkouba** [comment]
Hi @avp90 and thanks for reporting! The fix should pretty straightforward. Would you care to send a PR?

Also note that `PrettyTimeHelper` could use a different converter: https://github.com/trimou/trimou/blob/master/extensions/prettytime/src/main/java/org/trimou/prettytime/PrettyTimeHelper.java#L168. You should use `org.trimou.engine.MustacheEngineBuilder.registerHelper(String, Helper, boolean)` to overwrite the default helper registered by extension.

**Comment by avp90** [comment]
Hi @mkouba, i send you a PR today to fix the issue.
