### ISSUE TITLE
Tests fail in non-English locale

### ISSUE THREAD

**Issue by hwellmann** [trimou/trimou#49]
Apparently some tests assume to be running in an English locale - this assumption should be guaranteed or at least verified.

Running under `LANG=de_DE.UTF-8`, I get the following failures:

```
Failed tests: 
  ResourceBundleHelperTest.testInterpolation:57 expected:<H[ello,Hey,echo]> but was:<H[allo,He,oche]>
  ResourceBundleHelperTest.testFormat:83 expected:<H[e]llo Martin!> but was:<H[a]llo Martin!>
  ResourceBundleResolverTest.testInterpolation:52 expected:<H[e]llo> but was:<H[a]llo>
  ResourceBundleLambdaTest.testInterpolation:59 expected:<H[e]llo> but was:<H[a]llo>
```

**Comment by mkouba** [comment]
Hi @hwellmann, thanks for reporting. This is odd. The `ResourceBundleHelper` should use the `LocaleSupport`... Let me check the test again.

**Comment by mkouba** [comment]
You're right. The tests did not follow the exact lookup strategy, especially the `ResourceBundle.Control.getFallbackLocale(String, Locale)`. It should work now.
