### ISSUE TITLE
ClassPathTemplateLocator fails on JARs with non-null root path

### ISSUE THREAD

**Issue by hwellmann** [trimou/trimou#50]
Using this template locator
```
new ClassPathTemplateLocator(100, "trimou/shared", "trimou")
```
I'm getting the following exception:

```
org.trimou.exception.MustacheException: TEMPLATE_LOCATOR_INVALID_CONFIGURATION: Invalid root dir: file:/path/to/my.jar!/trimou/shared
	at org.trimou.engine.locator.FilePathTemplateLocator.checkRootDir(FilePathTemplateLocator.java:193)
	at org.trimou.engine.locator.ClassPathTemplateLocator.<init>(ClassPathTemplateLocator.java:101)
	at org.trimou.engine.locator.ClassPathTemplateLocator.<init>(ClassPathTemplateLocator.java:69)
```
The exception occurs when the resources are located in a JAR, it does not occur for exploded class folders.

`ClassPathTemplateLocator` extends `FilePathTemplateLocator` which looks a bit dodgy to me. In particular the method

```
File getRootDir()
```
does not really make sense for JARs or WARs. You may get a URL for a resource in an archive, but you can't always convert that URL to a File.

Moreover, it is legal for a JAR to contain no directory entries, so even when

```
jar:file:/path/to/my.jar!/trimou/shared/foo.trimou
```
exists
```
jar:file:/path/to/my.jar!/trimou/shared
```

may not exist.

**Comment by mkouba** [comment]
Ok. So for WARs you should always use the `ServletContextTemplateLocator` from the trimou-extension-servlet.
> ...but you can't always convert that URL to a File

Yep. That's true. Unfortunately, we don't have any test for a JAR...

> Moreover, it is legal for a JAR to contain no directory entries, so even when...

Hm, I didn't know this. In any case, `ClassPathTemplateLocator` should be rewritten to support JARs properly. The current version is usable if you don't require precompilation and pass `null` as a `rootPath`.

**Comment by hwellmann** [comment]
> Yep. That's true. Unfortunately, we don't have any test for a JAR...

It's easy to get false positives when running a unit test from Eclipse or Maven, because then the classes and resources of the current module will come from a class folder and not from a JAR. You'll probably have to use a proper Maven integration test, or use resources from another module of the same reactor.

**Comment by mkouba** [comment]
Sure, we will add one to our [integration tests](https://github.com/trimou/trimou/tree/master/integration-tests).

**Comment by hwellmann** [comment]
Here is a proposal for a solution:

https://github.com/hwellmann/org.ops4j.pax.warp/blob/master/pax-warp-core/src/main/java/org/ops4j/pax/warp/core/trimou/JarClassPathTemplateLocator.java

Should work even for weird classloaders, with the restriction that `getAllIdentifiers()` always returns an empty collection, so you can't precompile templates. Getting class scanning right is not exactly trivial, so why not keep it simple...

I'm happy to create a pull request based on this, if you think the appoach is ok, just let me know if this TemplateLocator shold be _added_ to the existing ones (under which name?) or simply _replace_ the current `ClassPathTemplateLocator`.

Or just feel free to copy and paste some bits and pieces, it's all ASL anyway...

**Comment by mkouba** [comment]
Looks good. Maybe we should try to find the templates if possible (i.e. use `ClassLoader.getResources()` and if the detected protocol is file:///...). I was also thinking about replacing the `ClassLoader.getResourceAsStream()` with `ClassLoader.getResources()` and log a warning if there are more than one resources found.

I wouldn't rename the `ClassPathTemplateLocator` but extend the `ClassPathTemplateLocator.Builder` instead (so that the user is able to decide).

I will try to update the current impl and then send a pull request for revision.
