### ISSUE TITLE
Improve trimou.org site

### ISSUE THREAD

**Issue by mkouba** [trimou/trimou#54]
Add some simple example and the list of interesting features a user might be interested in.

**Comment by mkouba** [comment]
https://github.com/trimou/trimou.github.io/commit/f4f43b7c01555dc2036616b31d1348b0f8496fc9

**Comment by mkouba** [comment]
@hwellmann @Pitzcarraldo Please check the new trimou.org. Any feedback is highly appreciated!  :-)

**Comment by hwellmann** [comment]
Cool, Trimou in a nutshell on one screen :-)
