### ISSUE TITLE
No meaningful exception messages

### ISSUE THREAD

**Issue by hwellmann** [trimou/trimou#93]
When loading a template with a syntax error, there is only a rather meaningless exception message

    org.trimou.exception.MustacheException: TEMPLATE_LOADING_ERROR: null

instead of helpful information like

    org.trimou.exception.MustacheException: COMPILE_INVALID_TEMPLATE: Incorrect last container segment on the stack: [type: SECTION, content: set, line: 9, idx: 23]

**Comment by mkouba** [comment]
Merged.
